In [3]:
#from machinelearningplus.com
import numpy as np

In [4]:
np.full((3, 3), True, dtype=bool)#create a boolean array

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#extract elements that satisfy a condition
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [8]:
#replace items that satisfy a condition
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [9]:
#reshaping an array
arr = np.arange(10)
arr.reshape(2, -1) #-1 automatically decides number of columns

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
#switch case using dictionary
def disp_dict(oper,x,y):
    return{
        'add':lambda:x+y,
        'sub':lambda:x-y,
        'mul':lambda:x*y,
        'div':lambda:x/y,
    }.get(oper,lambda:None)()

In [13]:
disp_dict('unknown',2,8)

In [14]:
def myfun(a,b):
    return a+b
funs=myfun


In [19]:
myfun(6,7)

13

In [18]:
funs[0](6,7)

13